### ISSUE TITLE
Hardware renderer crashes in Main class

### ISSUE THREAD

**Issue by BudgiePanic** [BudgiePanic/Connect3D#33]
In Main class, program crashes when trying to initialize Hardware renderer with the following exception:

> Exception in thread "main" java.lang.NoClassDefFoundError: org/lwjgl/Version
>	at connect3DRender.HardwareRenderer.initialize(HardwareRenderer.java:83)
>	at connect3DGame.Game.<init>(Game.java:55)
>	at connect3DMain.Main.main(Main.java:57)
>Caused by: java.lang.ClassNotFoundException: org.lwjgl.Version
>	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:583)
>	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
>	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521)
>	... 3 more

The exact same code works absolutely fine when the main method is moved to a different file, which makes this a very confusing error indeed.

**Comment by BudgiePanic** [comment]
No such error encountered on my Laptop. Seems to be specific to my Eclipse install.

**Comment by BudgiePanic** [comment]
I figured it out. Eclipse wasn't including the LWJGL3 library in the classpath entries for the Main classes' main method
![image](https://user-images.githubusercontent.com/50469074/150261960-cb471199-a0d9-44a5-ae6c-a30aa6f0f754.png)
